# Generated by Django 4.2 on 2025-03-04 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='UserCreationForm',
        ),
    ]
